name: "Sample React CI Pipeline / workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    build-end-test:
        runs-on: ubantu-latest


        steps:
            - name: "Setup Node JS"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "Check node version"
              run: node --version